# Generated by Django 4.1.4 on 2022-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_word_expression_word_languages_w_languag_5309e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phonetic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
