# Generated by Django 4.1.4 on 2022-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_word_phonetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phonetic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
