# Generated by Django 4.1.4 on 2022-12-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='language',
        ),
    ]
