# Generated by Django 4.1.4 on 2022-12-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_flashcard_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
